import { Post } from "./usePosts";

export const allPosts: Post[] = [
    {
        id: '1',
        name: 'Daniyal Nagori',
        username: 'daniyal-nagori-official',
        logo: './assets/logos/daniyal-nagori-official.jpg',
        message: 'فارم 47 کے مطابق یہ 1000 کا نوٹ ہے!',
        img: '/assets/images/post 1.jpeg',
        filter: 'following',
        createdAt: new Date(),
        myPost: false,
    },
    {
        id: '2',
        name: 'Asharib Ali',
        username: 'asharib-ali',
        logo: './assets/logos/asharib-ali.jpg',
        message: 'What do you do or wants todo: \nFrontend, Backend or Fullstack?',
        img: '/assets/images/post 2.jpeg',
        filter: 'following',
        createdAt: new Date(),
        myPost: false,
    },
    {
        id: '3',
        name: 'Asharib Ali',
        username: 'asharib-ali',
        logo: './assets/logos/asharib-ali.jpg',
        message: 'What do you do or wants todo: \nFrontend, Backend or Fullstack?',
        img: '/assets/images/post 2.jpeg',
        // poll: ['a', 'b', 'c'],
        filter: 'for-you',
        createdAt: new Date(),
        myPost: false,
    },
    {
        id: '4',
        name: 'Okasha Ijaz',
        username: 'okasha-ijaz',
        logo: './assets/logos/okasha-ijaz.jpg',
        message: 'Ready to mentor thousands in Full Stack Development and AI, building the future together.',
        img: '/assets/images/post 12.jpeg',
        filter: 'for-you',
        createdAt: new Date(),
        myPost: false,
    },
    {
        id: '5',
        name: 'Okasha Ijaz',
        username: 'okasha-ijaz',
        logo: './assets/logos/okasha-ijaz.jpg',
        message: 'Ready to mentor thousands in Full Stack Development and AI, building the future together.',
        img: '/assets/images/post 12.jpeg',
        filter: 'following',
        createdAt: new Date(),
        myPost: false,
    },
    {
        id: '6',
        name: 'Zia Khan',
        username: 'zia-khan',
        logo: './assets/logos/zia-khan.jpg',
        message: 'Sir Zia Ullah Khan, a graduate of Habib Public School, made history in 2024 by launching a large-scale initiative to teach artificial intelligence to the next generation.',
        img: '/assets/images/post 6.jpeg',
        filter: 'following',
        createdAt: new Date(),
        myPost: false,
    },
    {
        id: '7',
        name: 'Daniyal Nagori',
        username: 'daniyal-nagori-official',
        logo: './assets/logos/daniyal-nagori-official.jpg',
        message: 'تمام گٹھ جوڑ بے نقاب\n‏اللّٰہ الحق ہے',
        img: '/assets/images/post 4.jpeg',
        filter: 'following',
        createdAt: new Date(),
        myPost: false,
    },
    {
        id: '8',
        name: 'Daniyal Nagori',
        username: 'daniyal-nagori-official',
        logo: './assets/logos/daniyal-nagori-official.jpg',
        message: 'تمام گٹھ جوڑ بے نقاب\n‏اللّٰہ الحق ہے',
        img: '/assets/images/post 4.jpeg',
        filter: 'for-you',
        createdAt: new Date(),
        myPost: false,
    },
    {
        id: '9',
        name: 'Mr Beast',
        username: 'mrbeast',
        logo: './assets/logos/mrbeast.jpg',
        message: 'To celebrate my 26th birthday I’m giving away 26 Teslas on my instagram 🎉',
        img: '/assets/images/post 9.jpeg',
        filter: 'for-you',
        createdAt: new Date(),
        myPost: false,
    },
    {
        id: '10',
        name: 'Asharib Ali',
        username: 'asharib-ali',
        logo: './assets/logos/asharib-ali.jpg',
        message: 'When people ask, "What is your job?" 😖😁🤣\nMostly relatives and neighbour ask in my case, what about you?',
        img: '/assets/images/post 3.jpeg',
        filter: 'following',
        createdAt: new Date(),
        myPost: false,
    },
    {
        id: '11',
        name: 'Atia Khan',
        username: 'atiya-khan',
        logo: './assets/logos/atiya-khan.jpg',
        message: '🌟 Celebrating a Milestone: Graduation from the Emeritus Bootcamp🚀\nI\'m excited to tell you about my amazing experience at xLoop and the fantastic Emeritus Cloud Native Solution Development bootcamp, guided by remarkable',
        img: '/assets/images/post 10.jpeg',
        filter: 'for-you',
        createdAt: new Date(),
        myPost: false,
    },
    {
        id: '12',
        name: 'Atia Khan',
        username: 'atiya-khan',
        logo: './assets/logos/atiya-khan.jpg',
        message: '🌟 Celebrating a Milestone: Graduation from the Emeritus Bootcamp🚀\nI\'m excited to tell you about my amazing experience at xLoop and the fantastic Emeritus Cloud Native Solution Development bootcamp, guided by remarkable',
        img: '/assets/images/post 10.jpeg',
        filter: 'following',
        createdAt: new Date(),
        myPost: false,
    },
    {
        id: '13',
        name: 'Daniyal Nagori',
        username: 'daniyal-nagori-official',
        logo: './assets/logos/daniyal-nagori-official.jpg',
        img: '/assets/images/post 5.jpeg',
        filter: 'following',
        createdAt: new Date(),
        myPost: false,
    },
    {
        id: '14',
        name: 'Zia Khan',
        username: 'zia-khan',
        logo: './assets/logos/zia-khan.jpg',
        message: 'Received Tamgha-e- Imtiaz',
        img: '/assets/images/post 7.jpeg',
        filter: 'following',
        createdAt: new Date(),
        myPost: false,
    },
    {
        id: '15',
        name: 'Okasha Ijaz',
        username: 'okasha-ijaz',
        logo: './assets/logos/okasha-ikaz.jpg',
        message: 'You are building a website and want to schedule a system that sends emails to users at specific times. How can you achieve that? This is where cron jobs come into play.',
        img: '/assets/images/post 11.jpeg',
        filter: 'following',
        createdAt: new Date(),
        myPost: false,
    },
    {
        id: '16',
        name: 'Daniyal Nagori',
        username: 'daniyal-nagori-official',
        logo: './assets/logos/daniyal-nagori-official.jpg',
        message: 'پاکستانی میڈیا دنیا کی سب سے بڑی جھوٹ کی مشین ہے، یہ صحافت کے نام پر کالا دھبہ ہے۔ جب بھی کوئی چینل لگائیں تو ایسا لگتا ہے کہ ہمارا ملک سب سے آگے ہے اور سب کچھ ٹھیک ٹھاک چل رہا ہے لیکن حقیقت اس کے برعکس ہے،  مہنگائی عروج پر ہے اور بدامنی کی تو کوئی انتہا ہی نہیں لیکن حکمران ابھی بھی عیاشیوں میں ہیں ۔',
        filter: 'following',
        createdAt: new Date(),
        myPost: false,
    },
    {
        id: '17',
        name: 'Zia Khan',
        username: 'zia-khan',
        logo: './assets/logos/zia-khan.jpg',
        message: 'Received Tamgha-e- Imtiaz',
        img: '/assets/images/post 7.jpeg',
        filter: 'for-you',
        createdAt: new Date(),
        myPost: false,
    },
    {
        id: '18',
        name: 'Asharib Ali',
        username: 'asharib-ali',
        logo: './assets/logos/asharib-ali.jpg',
        message: 'Prove your’re a programmer without saying you are 😜\nlet me in the comments below 😅',
        img: '/assets/images/post 8.jpeg',
        filter: 'following',
        createdAt: new Date(),
        myPost: false,
    }
]